compile:
	f2py -c --fcompiler=gnu95 -m dssfpi1 fDSS1.f --f90flags="-Wtabs" 
	f2py -c --fcompiler=gnu95 -m dssfk1  fDSS1.f --f90flags="-Wtabs" 
	f2py -c --fcompiler=gnu95 -m dssfh  fDSS1.f --f90flags="-Wtabs" 
	f2py -c --fcompiler=gnu95 -m dssfpi2 fDSS2.f --f90flags="-Wtabs" 
	f2py -c --fcompiler=gnu95 -m dssfk2  fDSS2.f --f90flags="-Wtabs" 	
        	
	
